### PR TITLE
bug fix in transformation of 2D laser scans

### PR DESCRIPTION
**Pull request by kruesip**
I'm not 100% sure if this is correct, but I've tested it on a robot equipped with a 2D laser scanner, and it works (which was not the case with the previous version, since the ICP mapper expects the incoming point clouds to be represented in the scanner frame, and not in the odometry or whatever else frame).

If I understand it correctly, the whole point of this transformation at the beginning (when a new scan arrives) is to create a consistent point cloud, accounting for the motion during the acquisition, e.g., using the fixedFrame=odometry or another more-or-less-fixed frame.

### CODE REVIEW

**Comment by pomerlef** [comment]
Humm this is why I'm sad to not have any unit/system tests for those nodes... This will most probably have other implication. Did you also test with regular 3D applications?

**Comment by kruesip** [comment]
No, I haven't. But this function is only called if the input scans are sensor_msgs::LaserScan. From looking at the different launch files in the repository, I would assume that most people convert their scans to sensor_msgs::PointCloud2 externally, and hence don't use this function. That does not mean that nobody is using 2D scan inputs and still does 6D ICP, of course... But it's sort of hard to test for me, since I don't have a setup where this would make sense.

But you're right, this should probably be tested before we merge it. Right now, I just can't see why the 2D scans should be transformed to any other frame than the one in their message header, but maybe there's just something I don't see.

**Comment by pomerlef** [comment]
ok, we can give it a try. Can you investigate what is the cause of failure first?

**Comment by kruesip** [comment]
You mean the build failure? This is unrelated to my changes. In fact, for some reason Jenkins tries to build my newly created branch (that just happened automatically, I didn't set it up). But none of the other branches has ever been built, so I think the same error would appear there as well. Most probably just a problem of the Jenkins setup, since everything is fine on the various computers where I'm using the library.

**Comment by pomerlef** [comment]
Sorry for the delay!

**Pull request merged**
