### PR TITLE
Function name changes in libpointmatcher

### PR DESCRIPTION
**Pull request by lorenwel**
Changes to adapt to https://github.com/ethz-asl/libpointmatcher/pull/210. 

I don't use icp_mapping and I'm not set up to check if this breaks anything. I just want to get things going so we can merge the changes in libpointmatcher. 

@pomerlef @bochen87 Can one of you verify this PR?

### CODE REVIEW

**Comment by HannesSommer** [comment]
This is now only waiting for https://github.com/ethz-asl/libpointmatcher/pull/210 to get merged.

**Comment by HannesSommer** [comment]
@bochen87, you are using the branch `reintegrate/master_into_indigo_devel`, aren't you?

**Comment by HannesSommer** [comment]
test this please

**Comment by bochen87** [comment]
@HannesSommer yes, unfortunately I haven't come around to testing it yet, but will test it out next week and give you more feedback!

**Comment by bochen87** [comment]
I just tested it and it and there is still a compile error since function getMap() does not exist anymore and is called getPrefilteredMap() now. The dynamic_mapper.cpp has one call to that function.
Once replaced it does compile and first tests indicate that everything is still working. However, I haven't done any performance checks to verify whether this helps with performance on localization with larger point clouds.

**Comment by bochen87** [comment]
@lorenwel

**Comment by lorenwel** [comment]
@bochen87 I don't have write access and can't merge this. 
You need to ping some more people.

**Comment by HannesSommer** [comment]
retest this please

**Comment by HannesSommer** [comment]
Finally merging this :) because https://github.com/ethz-asl/libpointmatcher/pull/210 was merged. Thanks, @lorenwel and  @bochen87 !

**Pull request merged**
